/* CRIANDO UM USUÁRIO PARA O BANCO DE ESTUDOS */
CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;

/* CRIANDO A BASE DE DADOS PARA OS ESTUDOS */
CREATE DATABASE MY_SYSTEM;
USE MY_SYSTEM;


CREATE TABLE TB_CLIENTE (
	ID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    CPF VARCHAR(14) UNIQUE
);

INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Sônia Sebastiana Marcela Vieira', '013.288.769-00');
INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Mateus Miguel Ferreira', '524.680.012-14');
INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Elias Igor Ramos', '621.605.796-02');
INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Luna Marcela Gomes', '957.911.903-10');


CREATE TABLE TB_USERS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE TB_ROLES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHORITY VARCHAR(255)
);

CREATE TABLE TB_USERS_ROLES (
    USER_ID INT,
    ROLE_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES TB_USERS(ID),
	FOREIGN KEY (ROLE_ID) REFERENCES TB_ROLES(ID)
);

INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Steve Green', 'steve_user@email.com.br', '$2a$12$kvzDMZ9Kt5IDSWv6O8PrZOUbKJaXZC18a5lGmLojjmQ10fszhNuFi');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Stephanie Rose', 'stephanie_admin@email.com.br', '$2a$12$SpdZsp8Q.0t6Ne3uk.2gJ.JG3Lji6tgj.zUz50NSzZLgDJCrhVCAu');
INSERT INTO TB_USERS (NAME, EMAIL, PASSWORD) VALUES ('Joe Purple', 'joe_admin_user@email.com.br', '$2a$12$YXF60cto0VbkyA3BtGhbqu5XrL6yEVLPjlm/l1eKdahCwlhweZ9HW');

INSERT INTO TB_ROLES (AUTHORITY) VALUES ('USER');
INSERT INTO TB_ROLES (AUTHORITY) VALUES ('ADMIN');

INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (3, 1);
INSERT INTO TB_USERS_ROLES (USER_ID, ROLE_ID) VALUES (3, 2);

