CREATE DATABASE MY_SYSTEM;
USE MY_SYSTEM;

CREATE TABLE TB_CLIENTE (
	ID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    CPF VARCHAR(14) UNIQUE
);

INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Sônia Sebastiana Marcela Vieira', '013.288.769-00');
INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Mateus Miguel Ferreira', '524.680.012-14');
INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Elias Igor Ramos', '621.605.796-02');
INSERT INTO TB_CLIENTE (NOME, CPF) VALUES ('Luna Marcela Gomes', '957.911.903-10');

SELECT * FROM TB_CLIENTE;

